version: '3.8'

services:
  db:
    image: docker.io/postgres:13.0
    container_name: cod-wz-tournament-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cod-wz-tourney
      POSTGRES_PASSWORD: cod-wz-tourney
      POSTGRES_DB: cod-wz-tourney
