version: '3.8'

services:
  db:
    image: docker.io/postgres:13.2
    container_name: cod-wz-tournament-database
    ports:
      - "${PGPORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${PGUSER:-cod-wz-tourney}"
      POSTGRES_PASSWORD: "${PGPASSWORD:-cod-wz-tourney}"
      POSTGRES_DB: "${PGDATABASE:-cod-wz-tourney}"
