classDiagram
  class Tournament {
    +String name
    +Date startDate
    +Date endDate
    +int gameLimit
    +Roster roster
    +List~Team~ teams
    +bool isClosed
    +PointsCalculationRule pointsCalculationRule

    +createRandomTeams() List~Team~
    +getResults() List~Team~
  }

  class Roster {
    +String name
    +List~Player~ players
  }

  class Player {
    +String name
  }

  class Team {
    +String name
    +Player teamLeader
    +List~Player~ players
    +List~Game~ games
    +int placement

    +getTotalPoints() int
    +fetchGames(Date startDate, Date endDate, int limit) List~Game~
  }

  class Game {
    +Team team
    +List~PlayerResult~ playerResults
    +int placement

    +getPoints() int
  }

  class PlayerResult {
    +Player player
    +int kills
  }

  class PointsCalculationRule {
    +Object leftOperand
    +Object rightOperand
    +String operator

    +getResult() int
  }

  class User {
    +String name
    +String password
    +bool isAdmin
  }

  Tournament "1..*" o-- "1" Roster
  Tournament "1..*" o-- "1" PointsCalculationRule
  Tournament "1" *-- "1..*" Team
  Roster "1..*" o-- "1..*" Player
  Team "1..*" o-- "1..*" Player
  Team "1" *-- "1..*" Game
  Game "1" *-- "1..*" PlayerResult
  PlayerResult "1..*" o-- "1" Player
  PointsCalculationRule "1" *-- "0..2" PointsCalculationRule
  Player "0..1" o-- "0..1" User
